ARG DEBIAN=13.5

# use target Debian version as host
FROM debian:${DEBIAN} AS build

# define ARGS
ARG TXIKIJS=26.6.0

# install prerequisites
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt install -y build-essential cmake libffi-dev

# copy script files
WORKDIR /tmp
COPY ./download.sh .
COPY ./build.sh .

# download source
RUN chmod +x ./download.sh && ./download.sh ${TXIKIJS}

# build
RUN chmod +x ./build.sh && ./build.sh

# create blank image with only txikijs binary
FROM scratch AS final
COPY --from=build /tjs /
